FROM node:18

# Set working directory inside the container
WORKDIR /workspace

# Install TypeScript globally
RUN npm install -g typescript

# Default command to start the app
CMD ["npm", "run", "dev"]
